version: 0.8.{build}
environment:
  matrix:
    # array of all environments used to test builds
    - GENERATOR: NMake Makefiles
      CFG: Debug
      VS_VERSION: 12.0
    - GENERATOR: Visual Studio 14 2015
      VS_VERSION: 14.0
      CFG: Debug
    - GENERATOR: Visual Studio 12 2013
      VS_VERSION: 12.0
      CFG: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      CFG: Debug
      VS_VERSION: 14.0
    - GENERATOR: Visual Studio 12 2013 Win64
      CFG: Debug
      VS_VERSION: 12.0
install:
  - gem install asciidoctor
build:
  parallel: true
build_script:
  - cmd: IF NOT %VS_VERSION% == NONE call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
  - cmd: cmake --version
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" ..
  - cmd: cmake --build .
test_script:
  - cmd: ctest --output-on-failure -C "%CFG%"
