language: c
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
#    - os: osx
#      compiler: gcc
    - os: osx
      compiler: clang
# This section is required because the default Travis environment as of
# April 2016 has CMake 2.8.7 installed.
#addons:
#  apt:
#    sources:
#    # contains CMake 2.8.12
#    - kubuntu-backports
#    packages:
#    - cmake
script:
  # Print all environment variables to aid in CI development
  - printenv
  # Print version and available CMake generators to aid in CI development
  - cmake --version
  - cmake --help
  # Perform out-of-source build
  - mkdir build
  - cd build
  # Perform CMake backend generation, build, and test
  - cmake -DCMAKE_C_COMPILER=$CC ..
  - cmake --build .
  - ctest --output-on-failure -C Debug
deploy:
  provider: releases
  api_key:
    secure: fVMvvlhsginfIB7gEhAoKG7xzvF6D94yl8Z+jjfHQG4YtG3SScKVeQUnpWK7NhT90uoUfPnxd5dN3ZWlApoLBSz7iVD0sT1+VGYerM0Gn3LTUj3xvTB3WAAft6YePKhQeJfduzSNqsRjQ7buKgI1SFH0Ek5xwZe4Kl/O/D2Tsw0=
  file:
    - nanomsg-${TRAVIS_TAG}.zip
    - nanomsg-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: nanomsg/nanomsg
