version: 0.8.{build}
branches:
  except:
    - gh-pages
skip_tags: true
os: Windows Server 2012
environment:
  - NANOMSG_BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\build"
install:
  # enable calling pip directly
  - cmd: set PATH=%SystemDrive%\Python27\Scripts;%PATH%
  - cmd: pip install autobahntestsuite
before_build:
  - mkdir %NANOMSG_BUILD_DIR%
  - cd %NANOMSG_BUILD_DIR%
  - cmake -G "Visual Studio 12" %APPVEYOR_BUILD_FOLDER%
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  parallel: false
  project: %NANOMSG_BUILD_DIR%\ALL_BUILD.vcxproj
  verbosity: normal
test_script:
  - cmake --build . --target RUN_TESTS --config release
