version: 0.8.{build}
environment:
  matrix:
    # array of all environments used to test builds
#    - GENERATOR: Visual Studio 14 2015
#      CFG: Debug
#    - GENERATOR: Visual Studio 12 2013
#      CFG: Debug
#    - GENERATOR: Visual Studio 14 2015 Win64
#      CFG: Debug
#    - GENERATOR: Visual Studio 12 2013 Win64
#      CFG: Debug
    - GENERATOR: Visual Studio 11 2012
      CFG: Debug
    - GENERATOR: NMake Makefiles
      CFG: Debug
build:
  parallel: true
build_script:
  - cmd: cmake --version
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" ..
  - cmd: cmake --build .
test_script:
  - cmd: ctest --output-on-failure -C "%CFG%"
